RAW_ALERTS = "raw-alerts"
JIRA_INVESTIGATIONS = "jira-investigations"
ENRICHED_ALERTS = "enriched-alerts"
ORCHESTRATION_EVENTS = "orchestration-events"
CONTEXT_EVENTS = "context-events"
RESOLUTION_EVENTS = "resolution-events"
APPROVAL_EVENTS = "approval-events"
REMEDIATION_EVENTS = "remediation-events"
CLOSURE_EVENTS = "closure-events"
CLOSURE_LIFECYCLE_EVENTS = "closure-lifecycle-events"
REASSESSMENT_EVENTS = "incident-reassessment-events"
ROLLBACK_APPROVAL_EVENTS = "rollback-approval-events"
HITL_REVIEW_EVENTS = "hitl-review-events"
APPLICATION_ONBOARD_REQUESTED = "application.onboard.requested"
APPLICATION_DISCOVERY_COMPLETED = "application.discovery.completed"
APPLICATION_METRICS_VALIDATED = "application.metrics.validated"
APPLICATION_RULES_GENERATED = "application.rules.generated"
APPLICATION_PROMETHEUS_UPDATED = "application.prometheus.updated"
APPLICATION_VALIDATION_COMPLETED = "application.validation.completed"
APPLICATION_DASHBOARD_CREATED = "application.dashboard.created"
ALERT_RECEIVED_EVENT = "alert.received"
ALERT_NORMALIZED_EVENT = "alert.normalized"
ALERT_CONTEXT_REQUESTED_EVENT = "alert.context.requested"
ALERT_RCA_REQUESTED_EVENT = "alert.rca.requested"
ALERT_RESOLUTION_GENERATED_EVENT = "alert.resolution.generated"
APPROVAL_REQUESTED_EVENT = "approval.requested"
AUTOMATION_EXECUTED_EVENT = "automation.executed"

# Backward-compatible aliases retained for older imports.
ALERT_RECEIVED = ALERT_RECEIVED_EVENT
ALERT_NORMALIZED = ALERT_NORMALIZED_EVENT
ALERT_CONTEXT_REQUESTED = ALERT_CONTEXT_REQUESTED_EVENT
ALERT_RCA_REQUESTED = ALERT_RCA_REQUESTED_EVENT
RESOLUTION_GENERATED = ALERT_RESOLUTION_GENERATED_EVENT
APPROVAL_REQUESTED = APPROVAL_REQUESTED_EVENT
AUTOMATION_EXECUTED = AUTOMATION_EXECUTED_EVENT

# Versioned topic taxonomy for enterprise routing. Legacy topic names remain unchanged.
COMMANDS_TOPIC_V1 = "kaiops.commands.v1"
EVENTS_TOPIC_V1 = "kaiops.events.v1"
RESULTS_TOPIC_V1 = "kaiops.results.v1"
RETRY_TOPIC_V1 = "kaiops.retry.v1"
DEAD_LETTER_TOPIC_V1 = "kaiops.dlq.v1"
NOTIFICATIONS_TOPIC_V1 = "kaiops.notifications.v1"

ALL_TOPICS = [
    RAW_ALERTS,
    JIRA_INVESTIGATIONS,
    ENRICHED_ALERTS,
    ORCHESTRATION_EVENTS,
    CONTEXT_EVENTS,
    RESOLUTION_EVENTS,
    APPROVAL_EVENTS,
    REMEDIATION_EVENTS,
    CLOSURE_EVENTS,
    CLOSURE_LIFECYCLE_EVENTS,
    REASSESSMENT_EVENTS,
    ROLLBACK_APPROVAL_EVENTS,
    HITL_REVIEW_EVENTS,
    APPLICATION_ONBOARD_REQUESTED,
    APPLICATION_DISCOVERY_COMPLETED,
    APPLICATION_METRICS_VALIDATED,
    APPLICATION_RULES_GENERATED,
    APPLICATION_PROMETHEUS_UPDATED,
    APPLICATION_VALIDATION_COMPLETED,
    APPLICATION_DASHBOARD_CREATED,
    ALERT_RECEIVED_EVENT,
    ALERT_NORMALIZED_EVENT,
    ALERT_CONTEXT_REQUESTED_EVENT,
    ALERT_RCA_REQUESTED_EVENT,
    ALERT_RESOLUTION_GENERATED_EVENT,
    APPROVAL_REQUESTED_EVENT,
    AUTOMATION_EXECUTED_EVENT,
    COMMANDS_TOPIC_V1,
    EVENTS_TOPIC_V1,
    RESULTS_TOPIC_V1,
    RETRY_TOPIC_V1,
    DEAD_LETTER_TOPIC_V1,
    NOTIFICATIONS_TOPIC_V1,
]
